name: Deploy Frontend to Azure

on:
  push:
    branches: [main, master, develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      
      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp -r .next deploy/
          cp -r public deploy/ || true
          cp package.json deploy/
          cp package-lock.json deploy/
          cd deploy
          npm install --omit=dev
          cd ..
      
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: datchat-ui
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_FRONTEND }}
          package: deploy
