name: Deploy Backend to Azure

on:
  push:
    branches: [main, master, develop]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install root dependencies
        run: npm ci
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install
      
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: datchat-api
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_BACKEND }}
          package: ./backend
